# configuration for itranswarp:

spring:
  profiles:
    active: ${PROFILES:native}
  application:
    name: ${NAME:itranswarp}
    # default to empty (using server default timezone)
    timezone: ${TIMEZONE:}
  # MySQL configuration:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:it}?useSSL=${DB_SSL:false}&characterEncoding=utf8&serverTimezone=GMT
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      auto-commit: false
      connection-timeout: ${DB_TIMEOUT:3000}
      validation-timeout: ${DB_TIMEOUT:3000}
      max-lifetime: ${DB_MAX_LIFETIME:600000}
      maximum-pool-size: ${DB_POOL_SIZE:100}
      minimum-idle: ${DB_MIN_IDLE:1}
  # Redis configuration:
  redis:
    standalone:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:1}
  # Markdown plugins:
  markdown:
    plugins:
      # convert link to Bilibili video player, e.g. https://www.bilibili.com/video/av21322566
      bilibili:
        enabled: ${MARKDOWN_BILIBILI_ENABLED:true}
        width:   ${MARKDOWN_BILIBILI_WIDTH:100%}
        height:  ${MARKDOWN_BILIBILI_HEIGHT:480px}
      # convert link to QQ video player, e.g. https://v.qq.com/x/cover/3nd6v5g14aoo20t/j0859o1tww8.html
      qq-video:
        enabled: ${MARKDOWN_QQ_VIDEO_ENABLED:true}
        width:   ${MARKDOWN_QQ_VIDEO_WIDTH:100%}
        height:  ${MARKDOWN_QQ_VIDEO_HEIGHT:480px}
      # convert link to YouTube video player, e.g. https://www.youtube.com/watch?v=EaW6VcOzLT4
      youtube:
        enabled: ${MARKDOWN_YOUTUBE_ENABLED:true}
        width:   ${MARKDOWN_YOUTUBE_WIDTH:100%}
        height:  ${MARKDOWN_YOUTUBE_HEIGHT:480px}
      # convert securities to TradingView chart, e.g. $$NASDAQ:AAPL$$
      # search valid symbol name at https://www.tradingview.com/widget/advanced-chart/
      trading-view:
        enabled: ${MARKDOWN_TRADING_VIEW_ENABLED:true}
        width:   ${MARKDOWN_TRADING_VIEW_WIDTH:100%}
        height:  ${MARKDOWN_TRADING_VIEW_HEIGHT:480px}
  signin:
    password:
      enabled: ${SIGNIN_PASSWORD_ENABLED:true}
    # OAuth authentication configuration:
    # - name: display name
    # - icon: icon name, check https://getuikit.com/v2/docs/icon.html
    # - color: the button css background color, must be quoted by "".
    oauth:
      facebook:
        name:          "${OAUTH_FACEBOOK_NAME:Facebook}"
        icon:          "${OAUTH_FACEBOOK_ICON:facebook}"
        color:         "${OAUTH_FACEBOOK_COLOR:#3b5998}"
        client-id:     "${OAUTH_FACEBOOK_CLIENT_ID:}"
        client-secret: "${OAUTH_FACEBOOK_CLIENT_SECRET:}"
      github:
        name:          "${OAUTH_GITHUB_NAME:Github}"
        icon:          "${OAUTH_GITHUB_ICON:github}"
        color:         "${OAUTH_GITHUB_COLOR:#666666}"
        client-id:     "${OAUTH_GITHUB_CLIENT_ID:}"
        client-secret: "${OAUTH_GITHUB_CLIENT_SECRET:}"
      google:
        name:          "${OAUTH_GOOGLE_NAME:Google}"
        icon:          "${OAUTH_GOOGLE_ICON:google}"
        color:         "${OAUTH_GOOGLE_COLOR:#4285f4}"
        client-id:     "${OAUTH_GOOGLE_CLIENT_ID:}"
        client-secret: "${OAUTH_GOOGLE_CLIENT_SECRET:}"
      linkedin:
        name:          "${OAUTH_LINKEDIN_NAME:LinkedIn}"
        icon:          "${OAUTH_LINKEDIN_ICON:linkedin}"
        color:         "${OAUTH_LINKEDIN_COLOR:#007bb6}"
        client-id:     "${OAUTH_LINKEDIN_CLIENT_ID:}"
        client-secret: "${OAUTH_LINKEDIN_CLIENT_SECRET:}"
      microsoft:
        name:          "${OAUTH_MICROSOFT_NAME:Microsoft}"
        icon:          "${OAUTH_MICROSOFT_ICON:windows}"
        color:         "${OAUTH_MICROSOFT_COLOR:#2672ec}"
        client-id:     "${OAUTH_MICROSOFT_CLIENT_ID:}"
        client-secret: "${OAUTH_MICROSOFT_CLIENT_SECRET:}"
      qq:
        name:          "${OAUTH_QQ_NAME:QQ}"
        icon:          "${OAUTH_QQ_ICON:qq}"
        color:         "${OAUTH_QQ_COLOR:#00a8e6}"
        client-id:     "${OAUTH_QQ_CLIENT_ID:}"
        client-secret: "${OAUTH_QQ_CLIENT_SECRET:}"
      twitter:
        name:          "${OAUTH_TWITTER_NAME:Twitter}"
        icon:          "${OAUTH_TWITTER_ICON:facebook}"
        color:         "${OAUTH_TWITTER_COLOR:#1da1f2}"
        client-id:     "${OAUTH_TWITTER_CLIENT_ID:}"
        client-secret: "${OAUTH_TWITTER_CLIENT_SECRET:}"
      weibo:
        name:          "${OAUTH_WEIBO_NAME:Weibo}"
        icon:          "${OAUTH_WEIBO_ICON:weibo}"
        color:         "${OAUTH_WEIBO_COLOR:#e92b00}"
        client-id:     "${OAUTH_WEIBO_CLIENT_ID:}"
        client-secret: "${OAUTH_WEIBO_CLIENT_SECRET:}"
      yahoo:
        name:          "${OAUTH_YAHOO_NAME:Yahoo}"
        icon:          "${OAUTH_YAHOO_ICON:yahoo}"
        color:         "${OAUTH_YAHOO_COLOR:#720e9e}"
        client-id:     "${OAUTH_YAHOO_CLIENT_ID:}"
        client-secret: "${OAUTH_YAHOO_CLIENT_SECRET:}"

server:
  port: ${SERVER_PORT:2019}

encrypt:
  key: ${ENCRYPT_KEY:ChangeTheKeyWhenDeployProduction}
